[package]
name = "portability"
version = "0.1.0"
authors = ["Dzmitry Malyshau <kvark@mozilla.com>"]

[lib]
name = "portability"
crate-type = ["staticlib"]

[dependencies]
gfx_core = { path = "../gfx/src/core" }
gfx_backend_vulkan = { path = "../gfx/src/backend/vulkan", features = ["portable"] }
