[package]
name = "portability-gfx"
publish = false
version = "0.1.0"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Markus Siglreithmaier <m.siglreith@gmail.com>",
]

[lib]
name = "portability_gfx"

[features]
default = []
dispatch = []
#default = ["env_logger"] # uncomment for debugging

[dependencies]
lazy_static = "1.0"
log = "0.4"

[dependencies.env_logger]
version = "0.5"
optional = true

[dependencies.gfx-hal]
git = "https://github.com/gfx-rs/gfx"
rev = "4538593758d826cdcfc9f2de95dfc03c68624d05"

[target.'cfg(not(target_os = "macos"))'.dependencies.gfx-backend-vulkan]
git = "https://github.com/gfx-rs/gfx"
rev = "4538593758d826cdcfc9f2de95dfc03c68624d05"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
git = "https://github.com/gfx-rs/gfx"
rev = "4538593758d826cdcfc9f2de95dfc03c68624d05"
optional = true

[target.'cfg(target_os = "macos")'.dependencies.gfx-backend-metal]
git = "https://github.com/gfx-rs/gfx"
rev = "4538593758d826cdcfc9f2de95dfc03c68624d05"
optional = true
