[package]
name = "portability-gfx"
version = "0.1.0"
authors = ["Dzmitry Malyshau <kvark@mozilla.com>"]

[lib]
name = "portability_gfx"

[dependencies]
lazy_static = "1.0"

[dependencies.gfx-hal]
git = "https://github.com/gfx-rs/gfx"
branch = "portable"

[dependencies.gfx-backend-vulkan]
git = "https://github.com/gfx-rs/gfx"
branch = "portable"
features = ["portable"]
